### ISSUE TITLE
Some improvements possible

### ISSUE THREAD

**Issue by maxlandon** [tomlion/vim-solidity#15]
Hello, 

After installing the plug, I compared it with the ethereum package provided for Atom:
![screenshot from 2017-02-16 22-07-28](https://cloud.githubusercontent.com/assets/25826036/23041195/54929760-f494-11e6-8ad9-d3e59c800550.png)

I ended up with this output in Vim:
![screenshot from 2017-02-16 22-05-03](https://cloud.githubusercontent.com/assets/25826036/23041109/054ba5f2-f494-11e6-88f6-030616c9d489.png)

The newbie I am in Programming would like to know why there are such differences in the syntax highlighting. 
Is there room for improving the actual Vim syntax highlighting ? It lacks items such as def | extern | self. |  msg.sender | deposit | data, etc.... It does not recognize functions after 'def' for instance.
Otherwise, is there a way for me to change this by my own ?
Thanks.

**Comment by hiqua** [comment]
This is not a plugin for "ethereum", but for the Solidity language, so it cannot help you with your code (which is not Solidity code).
