### ISSUE TITLE
Don't override user settings without good reason

### ISSUE THREAD

**Issue by ays388** [tomlion/vim-solidity#16]
This plugin sets expandtab, tabstop=4 and softtabstop=4 for solidity files, overriding the value they are set to in vimrc.

A syntax plugin should only override such settings if there are good reasons to do so, such as tabs and spaces indent having a different meaning (like in e.g. python). That is not the case in solidity and you are just trying to force your coding style on everyone.
Please don't.

**Comment by Amarandus** [comment]
I think this can be closed because of PR https://github.com/tomlion/vim-solidity/pull/17

**Comment by ays388** [comment]
Agreed.
Next time you can close the issue automatically upon merging by writing "fixes #issuenumber" somewhere in your PR or commits.
